run:
  concurrency: 4                 # Number of concurrently running jobs
  timeout: 5m                    # Timeout duration for the operation
  modules-download-mode: readonly  # Download mode for modules (readonly)
  skip-dirs:
    - mempool                    # Directories to skip
    - state/indexer
    - state/txindex
  skip-files:
    - da/celestia/mock/server.go # Files to skip
    - ./*_test.go

linters:
  disable-all: true              # Disable all linters
  enable:                         # Enable specific linters
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo

issues:
  exclude-use-default: false     # Exclude issues that use default settings
