name: Build for macOS (AMD)

on: [ push ]

jobs:
  build:
    runs-on: arm-mac
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install GVM if not exists
        run: |
          source ~/.zshrc
          if ! command -v gvm &> /dev/null
          then
            echo "GVM could not be found, Installing now"
            bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
            echo "source ~/.gvm/scripts/gvm" >> ~/.zshrc
          fi
      - name: Install Go for GVM Bootstrap
        run: |
          source ~/.zshrc
          if ! command -v go &> /dev/null
          then
            echo "Go could not be found, Installing now"
            OS=$(uname -s | tr '[:upper:]' '[:lower:]')
            ARCH=$(uname -m)
            DOWNLOAD_URL="https://golang.org/dl/go1.17.13.$OS-$ARCH.tar.gz"
            curl -LO "$DOWNLOAD_URL"
            sudo tar -C /usr/local -xzf go1.17.13.$OS-$ARCH.tar.gz
            echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.zshrc
            echo "export GOROOT_BOOTSTRAP=\$(go env GOROOT)" >> ~/.zshrc
          fi
      - name: Check and Install Go versions if they do not exist
        run: |
          source ~/.zshrc
          if ! gvm list | grep -q 'go1.19'; then
            echo "Go 1.19 not found, Installing now"
            gvm install go1.19
          fi
          if ! gvm list | grep -q 'go1.20'; then
            echo "Go 1.20 not found, Installing now"
            gvm install go1.20
          fi
      - name: Run the roller build installation script
        run: |
          source ~/.zshrc
          gvm use go1.19
          chmod +x ./install.sh
          yes | ./install.sh
      - name: Clone or update Celestia Node repository
        run: |
          cd ~
          if [ -d "$HOME/celestia-node" ]; then
            cd celestia-node
            git fetch --all
          else
            git clone https://github.com/celestiaorg/celestia-node.git
            cd celestia-node
          fi
          git checkout tags/v0.11.0-rc6
      - name: Build Celestia Node
        run: |
          source ~/.zshrc
          gvm use go1.20
          cd
          cd celestia-node
          make build
          make go-install
          make cel-key
      - name: Create roller_bins folder structure
        run: |
          cd
          rm -rf roller_bins
          mkdir roller_bins
          mkdir roller_bins/lib
          sudo cp ./celestia-node/cel-key ./roller_bins/lib/cel-key
          sudo cp ./celestia-node/build/celestia ./roller_bins/lib/celestia
          sudo cp -r /usr/local/bin/roller_bins/* ./roller_bins/lib/
          sudo cp /usr/local/bin/roller ./roller_bins/roller
          sudo cp /usr/local/bin/rollapp_evm ./roller_bins/rollapp_evm
      - name: Archive the roller_bins folder
        run: |
          cd
          tar -czvf roller_v0.1.2_linux_amd64.tar.gz roller_bins
